name : github context

on: 
 workflow_dispatch
jobs:
 context:
  runs-on: ubuntu-latest
  steps:
   - name: print
     run: |
      echo 'Actor ${{github.actor}}'
      echo 'Event ${{github.event_name}}'
      echo 'Refrence detail ${{github.ref}}'
      echo 'Sha value ${{github.sha}}'
      echo 'Run detail value ${{github.run_id}}'
      echo 'runner number ${{github.run_number}}'
      
   
